#!/bin/bash

#
# Add web hosting accounts to the server
#

cd `dirname "$0"`
this_dir=`pwd`
cd ../
project_dir=`pwd`
config_file=$project_dir/config
test -f $config_file || die "No $config_file file found"
eval `cat config`

function die {
  echo "$0" >&2
  exit 1
}

if [ ! -z "$1" ]; then
  num_accounts="$1"
fi
if [ ! "$num_accounts" -gt 0 ]; then
  echo "Invalid num_accounts: $num_accounts"
  exit 2
fi

./client/upload || die "Failed to upload"
./client/ssh "./scripts/add_accounts $num_accounts" || die "Failed to add sites"
