#!/bin/bash

#
# Provision a server with base software and configuration
#

function die {
  echo "$0" >&2
  exit 1
}

cd `dirname "$0"`
cd ../

./client/upload || die "Failed to upload"
./client/ssh "./scripts/provision" || die "Failed to provision"
