#!/bin/bash -e

#
# Remove a hosting account by the given username
#

cd
source ./scripts/functions
read_config

name=$1
sudo rm -rf /var/www/$name.$root_hostname || /bin/true
sudo deluser $name --force --remove-home || /bin/true
