#!/bin/bash

#
# Called by cron, looks for and removes web hosting accounts
# that have expired.
#

# Close STDOUT file descriptor
exec 1<&-
# Close STDERR FD
exec 2<&-

# Open STDOUT as $LOG_FILE file for read and write.
exec 1>>$HOME/cleanup.log

# Redirect STDERR to STDOUT
exec 2>&1

echo "`date` START"

if [ ! -f $HOME/sites ]; then
  echo "`date` No sites to remove"
  exit 0
fi

source $HOME/script/functions

# Import $sites_ttl
read_config

created_at=`stat $HOME/sites | grep Change | sed 's/Change: //'`
echo "`date` created_at=$created_at"
expire_at=`date -d "$created_at+$sites_ttl"`
echo "`date` expire_at=$expire_at"
expire_at_int=`date -d "$expire_at" +%s`
now_int=`date +%s`
if [ $now_int -gt $expire_at_int ]; then
  echo "`date` Calling remove_accounts"
  echo "`date` CLEANUP" >> $HOME/cleanup_detail.log
  $HOME/scripts/remove_accounts >> $HOME/cleanup_detail.log 2>&1
else
  echo "`date` Sites are not expired"
fi

echo "`date` END"
